//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginHistory
    {
        public int IdHistory { get; set; }
        public int IdAdmin { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Admin Admin { get; set; }
    }
}
