//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalon
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public int IdSchedule { get; set; }
        public int IdMaster { get; set; }
        public int IdService { get; set; }
        public int IdClient { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual Master Master { get; set; }
        public virtual Service Service { get; set; }
    }
}
